# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

env:
  global:
  - GITHUB_REPO: antaldaniel/eurobarometer

language: R
cache: packages

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual
r_packages:
  - backports
  - vctrs
  - rlang
  - devtools
  - dplyr
  - tidyr
  - magrittr
  - purrr
  - tibble
  - ggplot2
  - tidyselect
  - stringr
  - lubridate
  - jsonlite
  - knitr
  - roxygen2
  - rvest
  - testthat
  - usethis
  - rmarkdown
  - knitr
  - kableExtra
  - sjlabelled
  - haven
  - rprojroot

r_github_packages:
  - jimhester/covr

warnings_are_errors: false
latex: false

before_install:
  - pip install --user codecov

jobs:
  include:
  - os:
     linux:
     dist: trusty
     sudo: required
     r: release
  - osx:
    osx_image: xcode11.6
    r: release
  - os:
     linux:
     dist: trusty
     sudo: required
     r: oldrel

notifications:
  email:
    - daniel.antal@ceemid.eu

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'
