# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

r:
- release
- oldrel

os: osx
osx_image: xcode11.6
latex: false

dist: trusty
sudo: required

warnings_are_errors: false

notifications:
  email:
    - daniel.antal@ceemid.eu

warnings_are_errors: false

r_packages:
  - backports
  - vctrs
  - rlang
  - devtools
  - dplyr
  - tidyr
  - magrittr
  - purrr
  - tibble
  - ggplot2
  - tidyselect
  - stringr
  - lubridate
  - jsonlite
  - knitr
  - roxygen2
  - rvest
  - testthat
  - usethis
  - rmarkdown
  - knitr
  - kableExtra
  - sjlabelled
  - haven
  - rprojroot

r_github_packages:
  - jimhester/covr

env:
  global:
  - GITHUB_REPO: antaldaniel/eurobarometer

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

before_install:
  - pip install --user codecov

after_success:
  - R -q -e 'covr::codecov(quiet = FALSE)'
