---
title: "Survey Data Harmonization"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Survey Data Harmonization}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(eurobarometer)
library(dplyr)
library(knitr)
library(stringr)
```

```{r}
ZA6863 <- read_rds(
  system.file("examples", "ZA6863.rds", package = "eurobarometer")
)
ZA7576 <- read_rds(
  system.file("examples", "ZA7576.rds", package = "eurobarometer")
)

```

```{r}
ZA6863_metadata <- gesis_metadata_create(ZA6863)
ZA7576_metadata <- gesis_metadata_create(ZA7576)
```

```{r}
ZA6863_items <- ZA6863_metadata %>%
  filter (
    class_orig %in% c("character", "numeric") | 
    str_sub(var_name_suggested, 1,5) == 'trust' ) %>%
  select (var_name_suggested) %>%
  filter ( var_name_suggested != 'not_given' ) %>%
  unlist() %>% as.character() 
```

```{r}
ZA7576_items <- ZA7576_metadata %>%
  filter (
    class_orig %in% c("character", "numeric") | 
    str_sub(var_name_suggested, 1,5) == 'trust' ) %>%
  select (var_name_suggested) %>%
  filter ( var_name_suggested != 'not_given' ) %>%
  unlist() %>% as.character()
```

```{r}
hZA6863 <- ZA6863 %>%
  stats::setNames ( nm = ZA6863_metadata$var_name_suggested ) %>%
  select ( all_of(intersect(ZA6863_items, ZA7576_items)))
```

```{r}
hZA7576 <- ZA7576 %>%
  stats::setNames ( nm = ZA6863_metadata$var_name_suggested ) %>%
  select ( all_of(intersect(ZA6863_items, ZA7576_items)))
```

```{r}
ZA6863_trust <- ZA6863_metadata %>%
  filter ( str_sub(var_name_suggested, 1,5) == 'trust' ) %>%
  select ( labels, na_levels ) %>%
  tidyr::unnest( cols = c(labels, na_levels) ) %>%
  distinct_all()

trust$labels[1]
trust$labels[2]
```

```{r}
ZA7576_trust <- ZA7576_metadata %>%
  filter ( str_sub(var_name_suggested, 1,5) == 'trust' ) %>%
  select ( labels, na_levels ) %>%
  tidyr::unnest( cols = c(labels, na_levels) ) %>%
  distinct_all()

ZA7576_trust$labels[1]
ZA7576_trust$labels[2]
```


```{r}
harmonize_trust <- function(x) {
   retroharmonize::harmonize_values(
  x = x,
  harmonize_label = NULL,
  harmonize_labels = (
    list (
     from = c("^Tend\\sto", "^Tend\\snot", "DK", "^Inap"),
    to  =  c("trust", "distrust", "do not know", "inap"), 
    numeric_values = c(1,0,99997, 99999 
    ))
    ),
  na_values = c(do_not_know = 99997, declined = 99998, inap = 99999),
  na_range = NULL,
  id = "survey_id",
  name_orig = NULL
)
}

labelled::val_labels(hZA7576$trust_army)
```

