#' ZA7562 Eurobarometer Sample
#'
#' A reduced part of a raw GESIS file to demonstrate changes in
#' variable labels and variable names.
#'
#' @format A data frame with 5074 rows in 48 variables:
#' \describe{
#'   \item{doi}{DIGITAL OBJECT IDENTIFIER}
#'   \item{isocntry}{COUNTRY CODE - ISO 3166}
#'   \item{p1}{DATE OF INTERVIEW}
#'   \item{p2}{TIME OF INTERVIEW}
#'   \item{p3}{DURATION OF INTERVIEW}
#'   \item{p4}{N OF PERSONS PRESENT DURING INTERVIEW}
#'   \item{p5}{RESPONDENT COOPERATION}
#'   \item{d7}{MARITAL STATUS}
#'   \item{d8}{AGE EDUCATION}
#'   \item{d25}{TYPE OF COMMUNITY}
#'   \item{d60}{DIFFICULTIES PAYING BILLS - LAST YEAR}
#'   \item{qa3_6}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa3_6}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa3_6}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa3_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa3_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa3_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa3_4}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa3_4}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa3_4}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa3_5}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa3_5}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa3_5}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa3_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa3_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa3_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa3_3}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa3_3}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa3_3}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{d71_1}{POLITICAL DISCUSSION - NATIONAL MATTERS}
#'   \item{d71_2}{POLITICAL DISCUSSION - EUROPEAN MATTERS}
#'   \item{d71_3}{POLITICAL DISCUSSION - LOCAL MATTERS}
#'   \item{qc9.1}{VACCINE INFO SOURCES: FAMILY}
#'   \item{qc9.2}{VACCINE INFO SOURCES: FRIENDS}
#'   \item{qc9.3}{VACCINE INFO SOURCES: DOCTOR ETC}
#'   \item{qc9.4}{VACCINE INFO SOURCES: OTHER HEALTH CARE WORKERS}
#'   \item{qc9.5}{VACCINE INFO SOURCES: PHARMACISTS}
#'   \item{qc9.6}{VACCINE INFO SOURCES: ONLINE SOCIAL NETWORKS}
#'   \item{qc9.7}{VACCINE INFO SOURCES: OTHER INTERNET SITES}
#'   \item{qc9.8}{VACCINE INFO SOURCES: HEALTH AUTHORITIES}
#'   \item{qc9.9}{VACCINE INFO SOURCES: OTHER (SPONT)}
#'   \item{qc9.10}{VACCINE INFO SOURCES: NONE (SPONT)}
#'   \item{qc9.11}{VACCINE INFO SOURCES: DK}
#'   \item{qc10}{MOST TRUSTED VACCINE INFO SOURCE}
#'   \item{d77}{POLITICAL DISCUSSION - CONVINCE FRIENDS}
#'   \item{w1}{WEIGHT RESULT FROM TARGET (REDRESSMENT)}
#'   \item{w3}{WEIGHT GERMANY}
#'   \item{wex}{WEIGHT EXTRAPOLATED POPULATION AGED 15+}
#'   }
#'   @source \href{https://www.gesis.org/index.php?id=12374}{Eurobarometer 91.2, March 2019, ZA No. 7562 on gesis.org}
#'   @seealso \code{\link{label_normalize}} for text normalization and
#'   \code{\link{label_suggest}} for canonisation.
"ZA7562_sample"
