#' ZA7576 Eurobarometer Sample
#'
#' A reduced part of a raw GESIS file to demonstrate changes in
#' variable labels and variable names.
#'
#'
#' @format A data frame with 5547 rows in 103 variables:
#' \describe{
#'   \item{doi}{DIGITAL OBJECT IDENTIFIER}
#'   \item{isocntry}{COUNTRY CODE - ISO 3166}
#'   \item{p1}{DATE OF INTERVIEW}
#'   \item{p2}{TIME OF INTERVIEW}
#'   \item{p3}{DURATION OF INTERVIEW}
#'   \item{p4}{N OF PERSONS PRESENT DURING INTERVIEW}
#'   \item{p5}{RESPONDENT COOPERATION}
#'   \item{d7}{MARITAL STATUS}
#'   \item{d8}{AGE EDUCATION}
#'   \item{d25}{TYPE OF COMMUNITY}
#'   \item{d60}{DIFFICULTIES PAYING BILLS - LAST YEAR}
#'   \item{qa14_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa14_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa14_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa14_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa14_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa14_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa14_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa14_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa14_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa14_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa14_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa14_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa14_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa14_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa14_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa14_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa14_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa14_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa14_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa14_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa6a_5}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa6a_5}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa6a_5}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa6a_5}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa6a_10}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa6a_10}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa6a_10}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa6a_10}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa6b_2}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa6b_2}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa6b_2}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa6b_2}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa6a_3}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa6a_3}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa6a_3}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa6a_3}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa6a_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa6a_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa6a_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa6a_1}{TRUST IN INSTITUTIONS: MEDIA}
#'   \item{qa6b_4}{TRUST IN INSTITUTIONS: MEDIA (TCC)}
#'   \item{qa6b_4}{TRUST IN INSTITUTIONS: MEDIA (TCC)}
#'   \item{qa6b_4}{TRUST IN INSTITUTIONS: MEDIA (TCC)}
#'   \item{qa6b_4}{TRUST IN INSTITUTIONS: MEDIA (TCC)}
#'   \item{qa6a_8}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa6a_8}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa6a_8}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa6a_8}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa6a_9}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa6a_9}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa6a_9}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa6a_9}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa6a_4}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa6a_4}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa6a_4}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa6a_4}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa6a_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa6a_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa6a_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa6a_2}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa6b_1}{TRUST IN INSTITUTIONS: POLITICAL PARTIES  (TCC)}
#'   \item{qa6b_1}{TRUST IN INSTITUTIONS: POLITICAL PARTIES  (TCC)}
#'   \item{qa6b_1}{TRUST IN INSTITUTIONS: POLITICAL PARTIES  (TCC)}
#'   \item{qa6b_1}{TRUST IN INSTITUTIONS: POLITICAL PARTIES  (TCC)}
#'   \item{qa6a_6}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa6a_6}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa6a_6}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa6a_6}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa6a_7}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa6a_7}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa6a_7}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa6a_7}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa6a_11}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa6a_11}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa6a_11}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa6a_11}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa6b_3}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa6b_3}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa6b_3}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa6b_3}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{d71a_1}{POLITICAL DISCUSSION - NATIONAL MATTERS}
#'   \item{d71a_2}{POLITICAL DISCUSSION - EUROPEAN MATTERS}
#'   \item{d71a_3}{POLITICAL DISCUSSION - LOCAL MATTERS}
#'   \item{d71b_1}{POLITICAL DISCUSSION - COMMUNITY MATTERS (CY-TCC)}
#'   \item{d71b_2}{POLITICAL DISCUSSION - EUROPEAN MATTERS (CY-TCC)}
#'   \item{d71b_3}{POLITICAL DISCUSSION - LOCAL MATTERS (CY-TCC)}
#'   \item{qg1b}{VOTERS - WHEN DECIDED TO VOTE}
#'   \item{qg8}{NON-VOTERS - WHEN DECIDED NOT TO VOTE}
#'   \item{d77}{POLITICAL DISCUSSION - CONVINCE FRIENDS}
#'   \item{w1}{WEIGHT RESULT FROM TARGET (REDRESSMENT)}
#'   \item{w3}{WEIGHT GERMANY}
#'   \item{wex}{WEIGHT EXTRAPOLATED POPULATION AGED 15+}
#'   }
#'   @source \href{https://www.gesis.org/index.php?id=12378}{Eurobarometer 91.5, June-July 2019, ZA No. 7576 on gesis.org}
#'   @seealso \code{\link{label_normalize}} for text normalization and
#'   \code{\link{label_suggest}} for canonisation.
"ZA7576_sample"
