#' ZA7489 Eurobarometer Sample
#'
#' A reduced part of a raw GESIS file to demonstrate changes in
#' variable labels and variable names.
#'
#' @format A data frame with 6613 rows in 131 variables:
#' \describe{
#'   \item{doi}{DIGITAL OBJECT IDENTIFIER}
#'   \item{isocntry}{COUNTRY CODE - ISO 3166}
#'   \item{p1}{DATE OF INTERVIEW}
#'   \item{p2}{TIME OF INTERVIEW}
#'   \item{p3}{DURATION OF INTERVIEW}
#'   \item{p4}{N OF PERSONS PRESENT DURING INTERVIEW}
#'   \item{p5}{RESPONDENT COOPERATION}
#'   \item{d7}{MARITAL STATUS}
#'   \item{d8}{AGE EDUCATION}
#'   \item{d25}{TYPE OF COMMUNITY}
#'   \item{d60}{DIFFICULTIES PAYING BILLS - LAST YEAR}
#'   \item{qa13_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa13_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa13_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa13_5}{COUNCIL OF THE EU - TRUST}
#'   \item{qa13_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa13_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa13_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa13_3}{EUROPEAN CENTRAL BANK - TRUST}
#'   \item{qa13_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa13_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa13_2}{EUROPEAN COMMISSION - TRUST}
#'   \item{qa13_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa13_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa13_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa13_4}{EUROPEAN COUNCIL - TRUST}
#'   \item{qa13_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa13_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa13_1}{EUROPEAN PARLIAMENT - TRUST}
#'   \item{qa8a_9}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa8a_9}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa8a_9}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa8a_9}{TRUST IN INSTITUTIONS: ARMY}
#'   \item{qa8a_14}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa8a_14}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa8a_14}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa8a_14}{TRUST IN INSTITUTIONS: EUROPEAN UNION}
#'   \item{qa8b_7}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa8b_7}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa8b_7}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa8b_7}{TRUST IN INSTITUTIONS: EUROPEAN UNION (TCC)}
#'   \item{qa8a_4}{TRUST IN INSTITUTIONS: INTERNET}
#'   \item{qa8a_4}{TRUST IN INSTITUTIONS: INTERNET}
#'   \item{qa8a_4}{TRUST IN INSTITUTIONS: INTERNET}
#'   \item{qa8a_4}{TRUST IN INSTITUTIONS: INTERNET}
#'   \item{qa8b_4}{TRUST IN INSTITUTIONS: INTERNET (TCC)}
#'   \item{qa8b_4}{TRUST IN INSTITUTIONS: INTERNET (TCC)}
#'   \item{qa8b_4}{TRUST IN INSTITUTIONS: INTERNET (TCC)}
#'   \item{qa8b_4}{TRUST IN INSTITUTIONS: INTERNET (TCC)}
#'   \item{qa8a_7}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa8a_7}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa8a_7}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa8a_7}{TRUST IN INSTITUTIONS: JUSTICE / LEGAL SYSTEM}
#'   \item{qa8a_12}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa8a_12}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa8a_12}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa8a_12}{TRUST IN INSTITUTIONS: NATIONAL GOVERNMENT}
#'   \item{qa8a_13}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa8a_13}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa8a_13}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa8a_13}{TRUST IN INSTITUTIONS: NATIONAL PARLIAMENT}
#'   \item{qa8a_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS}
#'   \item{qa8a_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS}
#'   \item{qa8a_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS}
#'   \item{qa8a_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS}
#'   \item{qa8b_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS (TCC)}
#'   \item{qa8b_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS (TCC)}
#'   \item{qa8b_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS (TCC)}
#'   \item{qa8b_5}{TRUST IN INSTITUTIONS: ONLINE SOCIAL NETWORKS (TCC)}
#'   \item{qa8a_8}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa8a_8}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa8a_8}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa8a_8}{TRUST IN INSTITUTIONS: POLICE}
#'   \item{qa8a_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa8a_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa8a_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa8a_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES}
#'   \item{qa8b_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES (TCC)}
#'   \item{qa8b_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES (TCC)}
#'   \item{qa8b_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES (TCC)}
#'   \item{qa8b_6}{TRUST IN INSTITUTIONS: POLITICAL PARTIES (TCC)}
#'   \item{qa8a_10}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa8a_10}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa8a_10}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa8a_10}{TRUST IN INSTITUTIONS: PUBLIC ADMINISTRATION}
#'   \item{qa8a_2}{TRUST IN INSTITUTIONS: RADIO}
#'   \item{qa8a_2}{TRUST IN INSTITUTIONS: RADIO}
#'   \item{qa8a_2}{TRUST IN INSTITUTIONS: RADIO}
#'   \item{qa8a_2}{TRUST IN INSTITUTIONS: RADIO}
#'   \item{qa8b_2}{TRUST IN INSTITUTIONS: RADIO (TCC)}
#'   \item{qa8b_2}{TRUST IN INSTITUTIONS: RADIO (TCC)}
#'   \item{qa8b_2}{TRUST IN INSTITUTIONS: RADIO (TCC)}
#'   \item{qa8b_2}{TRUST IN INSTITUTIONS: RADIO (TCC)}
#'   \item{qa8a_11}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa8a_11}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa8a_11}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa8a_11}{TRUST IN INSTITUTIONS: REG/LOCAL PUBLIC AUTHORITIES}
#'   \item{qa8a_3}{TRUST IN INSTITUTIONS: TELEVISION}
#'   \item{qa8a_3}{TRUST IN INSTITUTIONS: TELEVISION}
#'   \item{qa8a_3}{TRUST IN INSTITUTIONS: TELEVISION}
#'   \item{qa8a_3}{TRUST IN INSTITUTIONS: TELEVISION}
#'   \item{qa8b_3}{TRUST IN INSTITUTIONS: TELEVISION (TCC)}
#'   \item{qa8b_3}{TRUST IN INSTITUTIONS: TELEVISION (TCC)}
#'   \item{qa8b_3}{TRUST IN INSTITUTIONS: TELEVISION (TCC)}
#'   \item{qa8b_3}{TRUST IN INSTITUTIONS: TELEVISION (TCC)}
#'   \item{qa8a_15}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa8a_15}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa8a_15}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa8a_15}{TRUST IN INSTITUTIONS: UNITED NATIONS}
#'   \item{qa8b_8}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa8b_8}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa8b_8}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa8b_8}{TRUST IN INSTITUTIONS: UNITED NATIONS (TCC)}
#'   \item{qa8a_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS}
#'   \item{qa8a_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS}
#'   \item{qa8a_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS}
#'   \item{qa8a_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS}
#'   \item{qa8b_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS (TCC)}
#'   \item{qa8b_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS (TCC)}
#'   \item{qa8b_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS (TCC)}
#'   \item{qa8b_1}{TRUST IN INSTITUTIONS: WRITTEN PRESS (TCC)}
#'   \item{d71a_1}{POLITICAL DISCUSSION - NATIONAL MATTERS}
#'   \item{d71a_2}{POLITICAL DISCUSSION - EUROPEAN MATTERS}
#'   \item{d71a_3}{POLITICAL DISCUSSION - LOCAL MATTERS}
#'   \item{d71b_1}{POLITICAL DISCUSSION - COMMUNITY MATTERS (CY-TCC)}
#'   \item{d71b_2}{POLITICAL DISCUSSION - EUROPEAN MATTERS (CY-TCC)}
#'   \item{d71b_3}{POLITICAL DISCUSSION - LOCAL MATTERS (CY-TCC)}
#'   \item{d77}{POLITICAL DISCUSSION - CONVINCE FRIENDS}
#'   \item{w1}{WEIGHT RESULT FROM TARGET (REDRESSMENT)}
#'   \item{w3}{WEIGHT GERMANY}
#'   \item{wex}{WEIGHT EXTRAPOLATED POPULATION AGED 15+}
#'   }
#'   @source \href{https://www.gesis.org/index.php?id=12372}{Eurobarometer 90.3, November 2018, ZA No. 7489 on gesis.org}
#'   @seealso \code{\link{label_normalize}} for text normalization and
#'   \code{\link{label_suggest}} for canonisation.
"ZA7489_sample"
